INSERT INTO `localization` (`loc_key`, `loc_language`, `loc_val`) VALUES
('ACCOUNT_FORGOT_PASSWORD_EMAIL_BODY_STEP1', 'de', 'Hallo Wikiarguments Mitglied,\r\n<br><br>\r\nBitte folge diesem Link um ein neues Passwort anzufordern: [NEW_PASS_CONFIRM_LINK]\r\n<br><br>\r\nDein Wikiarguments Team'),
('ACCOUNT_FORGOT_PASSWORD_EMAIL_BODY_STEP2', 'de', 'Hallo Wikiarguments Mitglied,\r\n<br><br>\r\nwir haben ein neues Passwort generiert, mit welchem du dich jetzt auf Wikiarguments einloggen kannst.\r\n<br><br>\r\nDein neues Passwort lautet: [PASSWORD]\r\n<br><br>\r\nFür mehr Sicherheit, ändere nach dem Log-In dein Passwort erneut.\r\n<br><br>\r\nDein Wikiarguments Team'),
('ACCOUNT_FORGOT_PASSWORD_EMAIL_HEADER_STEP1', 'de', 'Passwort vergessen?'),
('ACCOUNT_FORGOT_PASSWORD_EMAIL_HEADER_STEP2', 'de', 'Dein neues Passwort'),
('CHARS_WRITTEN', 'de', 'Zeichen geschrieben'),
('CHARS_WRITTEN_LEFT', 'de', 'Zeichen übrig'),
('CHECKIN_CON_CONFIRMED', 'de', 'Stimme gezählt'),
('CHECKIN_PRO_CONFIRMED', 'de', 'Stimme gezählt'),
('ERROR_COUNTER_ARGUMENT_CHECK_IN_DIFF', 'de', 'Du kannst keine Gegenargumente in deiner eigenen Fraktion verfassen.'),
('ERROR_COUNTER_ARGUMENT_CHECK_IN_FIRST', 'de', 'Du musst einchecken bevor du Gegenargumente verfassen kannst.'),
('ERROR_INVALID_ARGUMENT', 'de', 'ERROR_INVALID_ARGUMENT'),
('ERROR_INVALID_FACTION', 'de', 'ERROR_INVALID_FACTION'),
('ERROR_INVALID_PROFILE', 'de', 'ERROR_INVALID_PROFILE'),
('ERROR_INVALID_QUESTION', 'de', 'Ungültige Frage.'),
('ERROR_NEW_ARGUMENT_MISSING_ABSTRACT', 'de', 'Bitte verfasse eine Zusammenfassung.'),
('ERROR_NEW_ARGUMENT_MISSING_DETAILS', 'de', 'ERROR_NEW_ARGUMENT_MISSING_DETAILS'),
('ERROR_NEW_ARGUMENT_MISSING_HEADLINE', 'de', 'Du musst eine Überschrift angeben.'),
('ERROR_NEW_ARGUMENT_TRY_AGAIN', 'de', 'Fehler. Bitte versuche es erneut.'),
('ERROR_NEW_QUESTION_INVALID_QUESTION', 'de', 'Ungültige Frage.'),
('ERROR_NEW_QUESTION_TRY_AGAIN', 'de', 'Fehler, bitte versuche es erneut.'),
('ERROR_NOT_CHECKED_IN', 'de', 'Du musst in Ja oder Nein eingecheckt sein um Argumente zu verfassen.'),
('ERROR_NOT_LOGGED_IN', 'de', 'Du musst eingeloggt sein um Argumente zu verfassen.'),
('ERROR_NO_PERMISSION', 'de', 'ERROR_NO_PERMISSION'),
('ERROR_PASS_REQUEST_MISSING_USERNAME', 'de', 'Du musst deinen Benutzernamen angeben.'),
('FOOTER_COPYRIGHT', 'de', '<a href="/imprint/">Impressum</a>\r\n'),
('FOOTER_OPEN_SOURCE', 'de', '<a href="https://code.google.com/p/wikiarguments/">Open Source</a>\r\n'),
('FOOTER_TOS', 'de', 'Nutzerinhalte stehen unter \r\n<a href="http://creativecommons.org/licenses/by/3.0/de/">CC BY 3.0</a>'),
('HEADER_NAVI_LOGOUT', 'de', 'Logout'),
('HEADER_NAVI_MANAGE_PROFILE', 'de', 'Einstellungen'),
('HEADER_NAVI_MY_PROFILE', 'de', 'Mein Profil'),
('HEADER_NAVI_NEW_QUESTION', 'de', 'Neue Frage'),
('HEADER_SIGNUP', 'de', 'Anmelden'),
('HTML_HEADER_META_LANG', 'de', 'de'),
('HTML_META_TITLE', 'de', ' - Wikiarguments'),
('HTML_META_TITLE_ARGUMENT', 'de', '[ARGUMENT] - Wikiarguments'),
('HTML_META_TITLE_IMPRINT', 'de', 'Imprint - Wikiarguments'),
('HTML_META_TITLE_MANAGE_PROFILE', 'de', 'Manage Profile - Wikiarguments'),
('HTML_META_TITLE_NEWEST', 'de', 'Neu - Wikiarguments'),
('HTML_META_TITLE_NEW_ARGUMENT', 'de', 'Neues Argument - Wikiarguments'),
('HTML_META_TITLE_NEW_COUNTER_ARGUMENT', 'de', 'Neues Gegenargument - Wikiarguments'),
('HTML_META_TITLE_NEW_QUESTION', 'de', 'Neue Frage - Wikiarguments'),
('HTML_META_TITLE_PROFILE', 'de', '[USERNAME] - Wikiarguments'),
('HTML_META_TITLE_QUESTION', 'de', '[QUESTION] - Wikiarguments'),
('HTML_META_TITLE_SIGNUP', 'de', 'Registrieren - Wikiarguments'),
('HTML_META_TITLE_TOP', 'de', 'Top - Wikiarguments'),
('HTML_META_TITLE_TRENDING', 'de', 'Im Trend - Wikiarguments'),
('LOGIN_ERROR_ACCOUNT_PENDING', 'de', 'Account pending'),
('LOGIN_ERROR_ALREADY_LOGGED_IN', 'de', 'Du bist bereits eingeloggt.'),
('LOGIN_ERROR_INVALID_PASSWORD', 'de', 'Falsches Passwort.'),
('LOGIN_ERROR_INVALID_USERNAME', 'de', 'Falscher Benutzername.'),
('LOGIN_FORGOT_PASSWORD', 'de', 'Passwort vergessen'),
('LOGIN_HEADLINE', 'de', 'Bereits registriert?<br />Hier einloggen:'),
('LOGIN_PASSWORD', 'de', 'Passwort'),
('LOGIN_SUBMIT', 'de', 'Login'),
('LOGIN_SUCCESS', 'de', 'Du hast dich erfolgreich angemeldet.'),
('LOGIN_USERNAME', 'de', 'Benutzername'),
('MANAGE_HEADLINE', 'de', 'Passwort ändern'),
('MANAGE_SUBMIT', 'de', 'Änderungen speichern'),
('NAVIGATION_NEWEST', 'de', 'Neu'),
('NAVIGATION_SEARCH_DEFAULT', 'de', 'suchen'),
('NAVIGATION_TOP', 'de', 'Top'),
('NAVIGATION_WHATS_HOT', 'de', 'Im Trend'),
('NEW_ARGUMENT', 'de', 'Argument hinzufügen'),
('NEW_ARGUMENT_ABSTRACT', 'de', 'Argument'),
('NEW_ARGUMENT_DETAILS', 'de', 'Argument </br>Details'),
('NEW_ARGUMENT_HEADLINE', 'de', 'Überschrift'),
('NEW_COUNTER_ARGUMENT', 'de', 'Gegenargument Hinzufügen'),
('NEW_QUESTION', 'de', 'Neue Frage'),
('NEW_QUESTION_DETAILS', 'de', 'Details'),
('NEW_QUESTION_HEADLINE', 'de', 'Neue Frage hinzufügen'),
('NEW_QUESTION_TAGS', 'de', 'Tags'),
('NEW_QUESTION_TITLE', 'de', 'Frage'),
('NOTICE_CHECKIN_NOT_LOGGED_IN', 'de', 'Du musst eingeloggt sein um dich einzuchecken.'),
('NOTICE_CONFIRMATION_ERROR_INVALID_USER', 'de', 'NOTICE_CONFIRMATION_ERROR_INVALID_USER'),
('NOTICE_CONFIRMATION_SUCCESS', 'de', 'Du hast dich erfolgreich registriert.'),
('NOTICE_NEW_ARGUMENT_NOT_CHECKED_IN', 'de', 'Du musst in Ja oder Nein eingecheckt sein um ein neues Argument zu verfassen.'),
('NOTICE_NEW_ARGUMENT_NOT_LOGGED_IN', 'de', 'Du musst eingeloggt sein um ein neues Argument zu verfassen.'),
('NOTICE_NEW_ARGUMENT_NO_PERMISSION', 'de', 'NOTICE_NEW_ARGUMENT_NO_PERMISSION'),
('NOTICE_NEW_COUNTER_ARGUMENT_NO_PERMISSION', 'de', 'NOTICE_NEW_COUNTER_ARGUMENT_NO_PERMISSION'),
('NOTICE_PASS_REQUEST_SUCCESS', 'de', 'Wir haben dir eine Email mit deinem neuen Passwort geschickt.'),
('NOTICE_VOTE_NOT_CHECKED_IN', 'de', 'Du musst in der jeweiligen Fraktion  eingecheckt sein um abzustimmen.'),
('NOTICE_VOTE_NOT_LOGGED_IN', 'de', 'Du musst eingeloggt sein um abzustimmen.'),
('NUM_COUNTER_ARGUMENTS', 'de', 'Gegen-argumente'),
('NUM_COUNTER_ARGUMENTS_NULL', 'de', 'Gegen-argumente'),
('NUM_COUNTER_ARGUMENTS_ONE', 'de', 'Gegen-argument'),
('NUM_COUNTER_ARGUMENTS_TWO', 'de', 'Gegen-argumente'),
('PAGE_ERROR_INVALID_PAGE', 'de', 'Diese Seite existiert nicht'),
('PAGINATION_PAGE_X_OF_Y', 'de', 'Seite [CUR] von [MAX]'),
('PASSWORD_OLD', 'de', 'Passwort alt'),
('PASS_REQUEST_SUCCESS', 'de', 'Wir haben dir eine Email geschickt um dein Passwort zur&uuml;ck zu setzen'),
('PROFILE_ARGUMENT_POINTS', 'de', 'Argument-Punkte'),
('PROFILE_HEADLINE', 'de', '[USERNAME]'),
('PROFILE_QUESTION_POINTS', 'de', 'Frage-Punkte'),
('PROFILE_SIGNUP_DATE', 'de', 'Anmelde-Datum: [SIGNUP_DATE]'),
('QUESTION_ARGUMENTS', 'de', '[NUM_ARGUMENTS]'),
('QUESTION_AUTHOR', 'de', 'Eingetragen [TIMESINCE] von [USERNAME]'),
('QUESTION_AUTHOR_ANON', 'de', 'Eingetragen [TIMESINCE]'),
('QUESTION_DISTRIBUTION_CON_PERC', 'de', 'Nein [PERC]%'),
('QUESTION_DISTRIBUTION_NUM_CHECKINS', 'de', '[NUM] Stimmen'),
('QUESTION_DISTRIBUTION_NUM_CHECKINS_NULL', 'de', '[NUM] Stimmen'),
('QUESTION_DISTRIBUTION_NUM_CHECKINS_ONE', 'de', '[NUM] Stimmen'),
('QUESTION_DISTRIBUTION_NUM_CHECKINS_TWO', 'de', '[NUM] Stimmen'),
('QUESTION_DISTRIBUTION_PRO_PERC', 'de', 'Ja [PERC]%'),
('QUESTION_OPTIONS', 'de', 'Optionen'),
('QUESTION_POINTS', 'de', 'Punkte'),
('QUESTION_POINTS_NULL', 'de', 'Punkte'),
('QUESTION_POINTS_ONE', 'de', 'Punkt'),
('QUESTION_POINTS_TWO', 'de', 'Punkte'),
('QUESTION_TAB_ARGUMENT', 'de', 'A:[TITLE]'),
('QUESTION_TAB_COUNTER_ARGUMENT', 'de', 'CA: [TITLE]'),
('QUESTION_TAB_DETAILS', 'de', 'Details'),
('QUESTION_TAB_DISCUSSION', 'de', 'Diskussion'),
('QUESTION_TAB_NEW_ARGUMENT', 'de', 'Neues Argument'),
('QUESTION_TAB_NEW_COUNTER_ARGUMENT', 'de', 'Neues Gegenargument'),
('READ_MORE', 'de', 'Read More >>'),
('REPORT_SPAM', 'de', 'Spam Melden'),
('SHARE_FACEBOOK', 'de', 'Facebook'),
('SHARE_TWITTER', 'de', 'Tweet'),
('SIGNUP_CONFIRMATION_EMAIL_BODY', 'de', 'Hallo [USERNAME],<br /><br />\r\n\r\n<a href = ''[CONFIRMATION_LINK]''>Klicke hier um deinen Wikiarguments Account freizuschalten.</a><br /><br />\r\nAlternativ kopiere diesen Link in deinen Browser: [CONFIRMATION_LINK]\r\n<br /><br />\r\nDein Wikiarguments Team'),
('SIGNUP_CONFIRMATION_EMAIL_SUBJECT', 'de', 'Wikiarguments Registration'),
('SIGNUP_EMAIL', 'de', 'Email'),
('SIGNUP_ERROR_ALREADY_LOGGED_IN', 'de', 'Du bist bereits eingeloggt.'),
('SIGNUP_ERROR_EMAIL_IN_USE', 'de', 'Diese Email wird bereits verwendet.'),
('SIGNUP_ERROR_GENERAL', 'de', 'Unbekannter Fehler'),
('SIGNUP_ERROR_INVALID_USERNAME', 'de', 'Ungültiger Benutzername'),
('SIGNUP_ERROR_PASSWORD_MISMATCH', 'de', 'Passwörter stimmen nicht überein!'),
('SIGNUP_ERROR_USERNAME_EXISTS', 'de', 'Dieser Benutzername existiert bereits.'),
('SIGNUP_HEADLINE', 'de', 'Registrieren'),
('SIGNUP_PASSWORD', 'de', 'Passwort'),
('SIGNUP_PASSWORD_REPEAT', 'de', 'Passwort wiederholen'),
('SIGNUP_SUBMIT', 'de', 'Registrieren'),
('SIGNUP_SUCCESS', 'de', 'Du hast eine Bestätigungsmail erhalten. Klicke auf den enthaltenen Link um deinen Account freizuschalten.'),
('SIGNUP_USERNAME', 'de', 'Benutzername'),
('SUBMIT_NEW_ARGUMENT', 'de', 'Abschicken'),
('SUBMIT_NEW_QUESTION', 'de', 'Frage stellen'),
('TAGS_DIVIDE', 'de', 'mit Kommata trennen'),
('TAGS_FILTER', 'de', 'Fragen mit dem Wort oder Tag "[TAGS]"'),
('TAGS_FILTER_REMOVE', 'de', 'Filter entfernen'),
('TIME_SINCE_DAYS', 'de', 'vor [DAYS] Tagen'),
('TIME_SINCE_DAYS_NULL', 'de', 'vor [DAYS] Tagen'),
('TIME_SINCE_DAYS_ONE', 'de', 'vor einem Tag'),
('TIME_SINCE_DAYS_TWO', 'de', 'vor [DAYS] Tagen'),
('TIME_SINCE_HOURS', 'de', 'vor [HOURS] Stunden'),
('TIME_SINCE_HOURS_NULL', 'de', 'vor [HOURS] Stunden'),
('TIME_SINCE_HOURS_ONE', 'de', 'vor einer Stunde'),
('TIME_SINCE_HOURS_TWO', 'de', 'vor [HOURS] Stunden'),
('TIME_SINCE_MINUTES', 'de', 'vor [MINUTES] Minuten'),
('TIME_SINCE_MINUTES_NULL', 'de', 'vor [MINUTES] Minuten'),
('TIME_SINCE_MINUTES_ONE', 'de', 'vor einer Minute'),
('TIME_SINCE_MINUTES_TWO', 'de', 'vor [MINUTES] Minuten'),
('TIME_SINCE_MONTHS', 'de', 'vor [MONTHS] Monaten'),
('TIME_SINCE_MONTHS_NULL', 'de', 'vor [MONTHS] Monaten'),
('TIME_SINCE_MONTHS_ONE', 'de', 'vor einem Monat'),
('TIME_SINCE_MONTHS_TWO', 'de', 'vor [MONTHS] Monaten'),
('TIME_SINCE_SECONDS', 'de', 'vor [SECONDS] Sekunden'),
('TIME_SINCE_SECONDS_NULL', 'de', 'vor [SECONDS] Sekunden'),
('TIME_SINCE_SECONDS_ONE', 'de', 'vor einer Sekunde'),
('TIME_SINCE_SECONDS_TWO', 'de', 'vor [SECONDS] Sekunden'),
('TIME_SINCE_YEARS', 'de', 'vor [YEARS] Jahren'),
('TIME_SINCE_YEARS_NULL', 'de', 'vor [YEARS] Jahren'),
('TIME_SINCE_YEARS_ONE', 'de', 'vor einem Jahr'),
('TIME_SINCE_YEARS_TWO', 'de', 'vor [YEARS] Jahren');

INSERT INTO `pages` (`pageId`, `pageTitle`, `url`, `className`, `templateFile`) VALUES
(1, 'default', 'default', 'PageDefault', 'default.php'),
(2, 'question', 'question', 'PageQuestion', 'question.php'),
(3, 'argument', 'argument', 'PageArgument', 'argument.php'),
(4, 'counter_argument', 'counter_argument', 'PageCounterArgument', 'counterArgument.php'),
(5, 'counter_argument_full', 'counter_argument_full', 'PageCounterArgumentFull', 'counterArgumentFull.php'),
(6, 'new_argument', 'new_argument', 'PageNewArgument', 'newArgument.php'),
(7, 'new_counter_argument', 'new_counter_argument', 'PageNewCounterArgument', 'newCounterArgument.php'),
(8, 'new_question', 'new_question', 'PageNewQuestion', 'newQuestion.php'),
(9, 'signup', 'signup', 'PageSignup', 'signup.php'),
(10, 'logout', 'logout', 'PageLogout', 'logout.php'),
(11, 'profile', 'profile', 'PageProfile', 'profile.php'),
(12, 'manage_profile', 'manage_profile', 'PageManageProfile', 'manageProfile.php'),
(13, 'imprint', 'imprint', 'PageImprint', 'imprint.php');

INSERT INTO `permissions` (`permissionId`, `groupId`, `action`, `state`) VALUES
(1, 0, 'login', -1);